Исправление бага с useNavigate после, которого сбрасывался window.title на стандартный index.html + коректировка стиля для .editDir который был привязна не к полю .changeDir, а к размеру к окна приложения
AuroraTeam/Launcher pull request #53
Opened 2024-12-13 10:18 UTC by StelStelox

2024-12-13 10:23 UTC, StelStelox commented
Я хз может есть другие способы исправления без UseEffect но этот вариант самый типизированный как я думаю

2024-12-13 10:47 UTC, StelStelox commented
![изображение](https://github.com/user-attachments/assets/4bc432b7-70bc-4233-bdbb-434bf0bbf168)

2024-12-13 11:04 UTC, StelStelox commented
Я думаю надо бновить hooks.ts setTitlebarTitleText

2024-12-13 11:06 UTC, StelStelox commented
и state.ts тоже

2024-12-13 13:54 UTC, JoCat requested changes

2024-12-13 13:54 UTC, JoCat commented on src/common/channels.ts
> +        TITLE: 'window:title',
SET_TITLE

2024-12-13 13:54 UTC, JoCat commented on src/common/channels.ts
> +        TITLE: 'window:title',
ну и window:setTitle соответственно

2024-12-13 13:54 UTC, JoCat commented on src/preload/components/Window.ts
> +    static title(title: string){
setTitle

2024-12-13 13:54 UTC, JoCat commented on src/preload/index.ts
> +        title: Window.title,
аналогично setTitle

2024-12-13 13:54 UTC, JoCat commented on src/renderer/runtime/components/TitleBar/index.tsx
> +            window.title = title.text;
чего?

2024-12-13 13:54 UTC, JoCat commented on src/preload/components/Window.ts
> +    static title(){
Не стоит так делать

2024-12-15 16:35 UTC, StelStelox commented
Ну тип правильно только настройки лаунчера ммммм)))
![изображение](https://github.com/user-attachments/assets/69441a6d-118b-438e-81fb-a433431c67d2)

2024-12-15 16:35 UTC, StelStelox commented
Если что после изменения экрана на стандартный всё становиться в норме. Aurora Launcher бдет отображаться

2024-12-15 19:26 UTC, JoCat approved these changes

2024-12-15 19:51 UTC, merged